# Generated by Django 5.2.14 on 2026-05-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_worksession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='checked_out_at',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('paused', 'Paused'), ('checked_out', 'Checked Out'), ('day_ended', 'Day Ended')], default='idle', max_length=15),
        ),
        migrations.CreateModel(
            name='WorkSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='attendance.worksession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
