# Generated by Django 5.2.14 on 2026-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('lead', 'Lead'), ('sme', 'SME'), ('mentor', 'Mentor'), ('staff', 'Staff'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
    ]
