# Generated by Django 5.2.15 on 2026-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('lead', 'Lead'), ('sme', 'SME'), ('mentor', 'Mentor'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
    ]
