# Generated by Django 5.2.3 on 2026-06-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('lead', 'Lead'), ('mentor', 'Mentor'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
    ]
