# Generated by Django 5.2.14 on 2026-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='intern_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('stipend', 'Stipend')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
