# Generated by Django 5.2.15 on 2026-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_intern_approved_at_intern_approved_by_intern_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='intern',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intern',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intern',
            name='shift_timing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='intern',
            name='year_of_passing',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
