# Generated by Django 6.0.5 on 2026-05-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SIMS', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('max_interns', models.IntegerField(default=50)),
                ('internship_duration_months', models.IntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
